POST /campaign-management-backend/auth/signin HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "username": "T14832",
  "password": "12345678"
}
###

POST /campaign-management-backend/auth/signin HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
"username": "E122005",
"password": "12345678"
}