GET /campaign-management-backend/campaign/all HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJUMTQ4MzIiLCJpYXQiOjE3MDE5NTQzNzAsImV4cCI6MTcwMjA3NzgyN30.pw1ilBg93rr-eFkUDrhy_J7XzWFtfi1Hiu5nIAlc1ZQ

###
# getting campaigns being unauthorized.
GET /campaign-management-backend/campaign/all HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Authorization: Bearer

###
# Deleting campaign.
DELETE /campaign-management-backend/campaign/delete/000001 HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJUMTQ4MzIiLCJpYXQiOjE3MDE5NTQzNzAsImV4cCI6MTcwMjA3NzgyN30.pw1ilBg93rr-eFkUDrhy_J7XzWFtfi1Hiu5nIAlc1ZQ

###
# Deleting all campaigns
DELETE /campaign-management-backend/campaign/delete/selected-campaigns
Host: localhost:8080
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJUMTQ4MzIiLCJpYXQiOjE3MDE5NTQzNzAsImV4cCI6MTcwMjA3NzgyN30.pw1ilBg93rr-eFkUDrhy_J7XzWFtfi1Hiu5nIAlc1ZQ

{
  "selectedCampaigns": [
    {
      "campaignId": "000001",
      "campaignFolderId": null,
      "title": "Construction Product Campaign 000001",
      "startDate": "2024-07-20T08:30:00.000+00:00",
      "endDate": "2024-08-20T08:30:00.000+00:00",
      "type": 9001,
      "promoDescriptionText": "Shop now for a wide range of construction products at discounted prices. Limited stock available!",
      "promoSummaryText": "Save Big on Construction Products",
      "ribbonType": "Special Offer",
      "termsUrl": "abc",
      "campaignClientGroups": [
        "REST"
      ],
      "campaignTags": [],
      "rootIndicator": true,
      "filterImgUrl": "filter_image.jpg",
      "filterOverlayText": "Limited Time Offer",
      "promoImgUrl": "promo_image.jpg",
      "promoImgAltText": "abc",
      "campaignWebsiteUrl": "https://constructionproductscampaign.com",
      "campaignWebsiteText": "Learn More",
      "appTitle": "Construction Products App",
      "appImageUrl": "app_image.jpg",
      "appSummary": "Explore and purchase construction products on the go. Get exclusive discounts and offers!",
      "relativeUrl": "campaign-actie/page",
      "campaignItems": [
        {
          "campaignItemId": "000001",
          "promoTitle": "Product 000001000001",
          "promoText": "Promo text for Product 000001000001",
          "promoImgUrl": "product_image1.jpg",
          "promoImgAltText": null,
          "weight": "M",
          "teaser": "Teaser 1",
          "extraText": "Extra Text 1",
          "campaignItemDiscounts": [
            {
              "discountId": "000001",
              "tuPoints": 5,
              "altSkuImgUrl": null,
              "skuIds": [
                "00032123",
                "2239221"
              ],
              "discountPrice": {
                "discountId": "000001",
                "price": 20.0
              },
              "discountPercentage": null
            }
          ]
        }
      ]
    },
    {
      "campaignId": "000002",
      "campaignFolderId": null,
      "title": "Construction Product Campaign 000002",
      "startDate": "2024-07-20T08:30:00.000+00:00",
      "endDate": "2024-08-20T08:30:00.000+00:00",
      "type": 9001,
      "promoDescriptionText": "Shop now for a wide range of construction products at discounted prices. Limited stock available!",
      "promoSummaryText": "Save Big on Construction Products",
      "ribbonType": "Special Offer",
      "termsUrl": "abc",
      "campaignClientGroups": [
        "REST"
      ],
      "campaignTags": [],
      "rootIndicator": true,
      "filterImgUrl": "filter_image.jpg",
      "filterOverlayText": "Limited Time Offer",
      "promoImgUrl": "promo_image.jpg",
      "promoImgAltText": "abc",
      "campaignWebsiteUrl": "https://constructionproductscampaign.com",
      "campaignWebsiteText": "Learn More",
      "appTitle": "Construction Products App",
      "appImageUrl": "app_image.jpg",
      "appSummary": "Explore and purchase construction products on the go. Get exclusive discounts and offers!",
      "relativeUrl": "campaign-actie/page",
      "campaignItems": [
        {
          "campaignItemId": "000002",
          "promoTitle": "Product 000001000001",
          "promoText": "Promo text for Product 000001000002",
          "promoImgUrl": "product_image1.jpg",
          "promoImgAltText": null,
          "weight": "M",
          "teaser": "Teaser 1",
          "extraText": "Extra Text 1",
          "campaignItemDiscounts": [
            {
              "discountId": "000002",
              "tuPoints": 5,
              "altSkuImgUrl": null,
              "skuIds": [
                "00032123",
                "2239221"
              ],
              "discountPrice": {
                "discountId": "000002",
                "price": 20.0
              },
              "discountPercentage": null
            }
          ]
        }
      ]
    },
    {
      "campaignId": "000003",
      "campaignFolderId": null,
      "title": "Construction Product Campaign 000003",
      "startDate": "2024-07-20T08:30:00.000+00:00",
      "endDate": "2024-08-20T08:30:00.000+00:00",
      "type": 9001,
      "promoDescriptionText": "Shop now for a wide range of construction products at discounted prices. Limited stock available!",
      "promoSummaryText": "Save Big on Construction Products",
      "ribbonType": "Special Offer",
      "termsUrl": "abc",
      "campaignClientGroups": [
        "REST"
      ],
      "campaignTags": [],
      "rootIndicator": true,
      "filterImgUrl": "filter_image.jpg",
      "filterOverlayText": "Limited Time Offer",
      "promoImgUrl": "promo_image.jpg",
      "promoImgAltText": "abc",
      "campaignWebsiteUrl": "https://constructionproductscampaign.com",
      "campaignWebsiteText": "Learn More",
      "appTitle": "Construction Products App",
      "appImageUrl": "app_image.jpg",
      "appSummary": "Explore and purchase construction products on the go. Get exclusive discounts and offers!",
      "relativeUrl": "campaign-actie/page",
      "campaignItems": [
        {
          "campaignItemId": "000003",
          "promoTitle": "Product 000001000001",
          "promoText": "Promo text for Product 000001000003",
          "promoImgUrl": "product_image1.jpg",
          "promoImgAltText": null,
          "weight": "M",
          "teaser": "Teaser 1",
          "extraText": "Extra Text 1",
          "campaignItemDiscounts": [
            {
              "discountId": "000003",
              "tuPoints": 5,
              "altSkuImgUrl": null,
              "skuIds": [
                "00032123",
                "2239221"
              ],
              "discountPrice": {
                "discountId": "000003",
                "price": 20.0
              },
              "discountPercentage": null
            }
          ]
        }
      ]
    }
  ]
}


###
# Adding campaign.
POST /campaign-management-backend/campaign HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJUMTQ4MzIiLCJpYXQiOjE3MDE5NTQzNzAsImV4cCI6MTcwMjA3NzgyN30.pw1ilBg93rr-eFkUDrhy_J7XzWFtfi1Hiu5nIAlc1ZQ

{
  "campaignId": null,
  "campaignFolderId": null,
  "title": "Test Campaign",
  "startDate": "2023-07-13T15:28:36.000+00:00",
  "endDate": "2023-08-04T18:11:16.000+00:00",
  "type": 9001,
  "promoDescriptionText": "Shop now for a wide range of construction products at discounted prices. Limited stock available!",
  "promoSummaryText": "Save Big on Construction Products",
  "ribbonType": "Special Offer",
  "termsUrl": "abc",
  "campaignClientGroups": [
    "Industrie"
  ],
  "campaignTags": [],
  "rootIndicator": true,
  "filterImgUrl": "filter_image.jpg",
  "filterOverlayText": "Limited Time Offer!",
  "promoImgUrl": "promo_image.jpg",
  "promoImgAltText": "abc",
  "campaignWebsiteUrl": "https://constructionproductscampaign.com",
  "campaignWebsiteText": "Learn More",
  "appTitle": "Construction Products App",
  "appImageUrl": "app_image.jpg",
  "appSummary": "Explore and purchase construction products on the go. Get exclusive discounts and offers!",
  "relativeUrl": null,
  "campaignItems": [
  ]
}