GET /api/campaign/all HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJUMTQ4MzIiLCJpYXQiOjE2ODk3NzA2NzEsImV4cCI6MTY4OTg5NDEyOH0.ztinAIy7pHk9qAw3QryNZ4KpJW4YAjvwC8AkGU9-XiY

###
# getting campaigns being unauthorized.
GET /api/campaign/all HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJFMTIyMDA1IiwiaWF0IjoxNjg5MDc0NTI4LCJleHAiOjE2ODkxOTc5ODV9.e6F50-WFwMeDPReUkLw7l78_ZlxQ3CigBhBR9tCGjfU

###
# Deleting campaign.
DELETE /api/campaign/delete/000001 HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJUMTQ4MzIiLCJpYXQiOjE2ODk3NzA2NzEsImV4cCI6MTY4OTg5NDEyOH0.ztinAIy7pHk9qAw3QryNZ4KpJW4YAjvwC8AkGU9-XiY

###
# Deleting all campaigns
DELETE /api/campaign/delete/selected-campaigns
Host: localhost:8080
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJUMTQ4MzIiLCJpYXQiOjE2ODk3NzA2NzEsImV4cCI6MTY4OTg5NDEyOH0.ztinAIy7pHk9qAw3QryNZ4KpJW4YAjvwC8AkGU9-XiY

{
  "selectedCampaigns": [
    {
      "campaignId": "000001",
      "campaignFolderId": null,
      "title": "Construction Product Campaign 000001",
      "startDate": "2023-07-18T14:39:09.000+00:00",
      "endDate": "2023-08-12T21:13:10.000+00:00",
      "type": 9001,
      "promoDescriptionText": "Shop now for a wide range of construction products at discounted prices. Limited stock available!",
      "promoSummaryText": "Save Big on Construction Products",
      "ribbonType": "Special Offer",
      "termsUrl": "abc",
      "campaignClientGroups": [
        "Industrie"
      ],
      "campaignTags": [],
      "rootIndicator": true,
      "filterImgUrl": "filter_image.jpg",
      "filterOverlayText": "Limited Time Offer!",
      "promoImgUrl": "promo_image.jpg",
      "promoImgAltText": "abc",
      "campaignWebsiteUrl": "https://constructionproductscampaign.com",
      "campaignWebsiteText": "Learn More",
      "appTitle": "Construction Products App",
      "appImageUrl": "app_image.jpg",
      "appSummary": "Explore and purchase construction products on the go. Get exclusive discounts and offers!",
      "relativeUrl": null,
      "campaignItems": [
        {
          "campaignItemId": "000001000001",
          "promoTitle": "Product 000001000001",
          "promoText": "Promo text for Product 000001000001",
          "promoImgUrl": "product_image1.jpg",
          "promoImgAltText": null,
          "weight": "1",
          "teaser": "Teaser 1",
          "extraText": "Extra Text 1",
          "campaignItemDiscounts": [
            {
              "discountId": "000001000001_D",
              "tuPoints": 5,
              "altSkuImgUrl": null,
              "skuId": [],
              "discountPrice": {
                "discountId": "000001000001_D",
                "price": 20.0
              },
              "discountPercentage": null
            }
          ]
        },
        {
          "campaignItemId": "000001000002",
          "promoTitle": "Product 000001000002",
          "promoText": "Promo text for Product 000001000002",
          "promoImgUrl": "product_image2.jpg",
          "promoImgAltText": null,
          "weight": "2",
          "teaser": "Teaser 2",
          "extraText": "Extra Text 2",
          "campaignItemDiscounts": [
            {
              "discountId": "000001000002_D",
              "tuPoints": 5,
              "altSkuImgUrl": null,
              "skuId": [],
              "discountPrice": {
                "discountId": "000001000002_D",
                "price": 20.0
              },
              "discountPercentage": null
            }
          ]
        },
        {
          "campaignItemId": "000001000003",
          "promoTitle": "Product 000001000003",
          "promoText": "Promo text for Product 000001000003",
          "promoImgUrl": "product_image3.jpg",
          "promoImgAltText": null,
          "weight": "3",
          "teaser": "Teaser 3",
          "extraText": "Extra Text 3",
          "campaignItemDiscounts": [
            {
              "discountId": "000001000003_D",
              "tuPoints": 5,
              "altSkuImgUrl": null,
              "skuId": [],
              "discountPrice": {
                "discountId": "000001000003_D",
                "price": 20.0
              },
              "discountPercentage": null
            }
          ]
        }
      ]
    },
    {
      "campaignId": "000002",
      "campaignFolderId": null,
      "title": "Construction Product Campaign 000002",
      "startDate": "2023-07-18T14:39:09.000+00:00",
      "endDate": "2023-08-09T00:16:25.000+00:00",
      "type": 9001,
      "promoDescriptionText": "Shop now for a wide range of construction products at discounted prices. Limited stock available!",
      "promoSummaryText": "Save Big on Construction Products",
      "ribbonType": "Special Offer",
      "termsUrl": "abc",
      "campaignClientGroups": [
        "Industrie"
      ],
      "campaignTags": [
        "Tag1",
        "Tag2"
      ],
      "rootIndicator": true,
      "filterImgUrl": "filter_image.jpg",
      "filterOverlayText": "Limited Time Offer!",
      "promoImgUrl": "promo_image.jpg",
      "promoImgAltText": "abc",
      "campaignWebsiteUrl": "https://constructionproductscampaign.com",
      "campaignWebsiteText": "Learn More",
      "appTitle": "Construction Products App",
      "appImageUrl": "app_image.jpg",
      "appSummary": "Explore and purchase construction products on the go. Get exclusive discounts and offers!",
      "relativeUrl": null,
      "campaignItems": [
        {
          "campaignItemId": "000002000001",
          "promoTitle": "Product 000002000001",
          "promoText": "Promo text for Product 000002000001",
          "promoImgUrl": "product_image1.jpg",
          "promoImgAltText": null,
          "weight": "1",
          "teaser": "Teaser 1",
          "extraText": "Extra Text 1",
          "campaignItemDiscounts": [
            {
              "discountId": "000002000001_D",
              "tuPoints": 5,
              "altSkuImgUrl": null,
              "skuId": [],
              "discountPrice": {
                "discountId": "000002000001_D",
                "price": 20.0
              },
              "discountPercentage": null
            }
          ]
        },
        {
          "campaignItemId": "000002000002",
          "promoTitle": "Product 000002000002",
          "promoText": "Promo text for Product 000002000002",
          "promoImgUrl": "product_image2.jpg",
          "promoImgAltText": null,
          "weight": "2",
          "teaser": "Teaser 2",
          "extraText": "Extra Text 2",
          "campaignItemDiscounts": [
            {
              "discountId": "000002000002_D",
              "tuPoints": 5,
              "altSkuImgUrl": null,
              "skuId": [],
              "discountPrice": {
                "discountId": "000002000002_D",
                "price": 20.0
              },
              "discountPercentage": null
            }
          ]
        },
        {
          "campaignItemId": "000002000003",
          "promoTitle": "Product 000002000003",
          "promoText": "Promo text for Product 000002000003",
          "promoImgUrl": "product_image3.jpg",
          "promoImgAltText": null,
          "weight": "3",
          "teaser": "Teaser 3",
          "extraText": "Extra Text 3",
          "campaignItemDiscounts": [
            {
              "discountId": "000002000003_D",
              "tuPoints": 5,
              "altSkuImgUrl": null,
              "skuId": [],
              "discountPrice": {
                "discountId": "000002000003_D",
                "price": 20.0
              },
              "discountPercentage": null
            }
          ]
        }
      ]
    },
    {
      "campaignId": "000003",
      "campaignFolderId": null,
      "title": "Construction Product Campaign 000003",
      "startDate": "2023-07-18T14:39:09.000+00:00",
      "endDate": "2023-07-22T09:59:52.000+00:00",
      "type": 9001,
      "promoDescriptionText": "Shop now for a wide range of construction products at discounted prices. Limited stock available!",
      "promoSummaryText": "Save Big on Construction Products",
      "ribbonType": "Special Offer",
      "termsUrl": "abc",
      "campaignClientGroups": [
        "Industrie"
      ],
      "campaignTags": [],
      "rootIndicator": true,
      "filterImgUrl": "filter_image.jpg",
      "filterOverlayText": "Limited Time Offer!",
      "promoImgUrl": "promo_image.jpg",
      "promoImgAltText": "abc",
      "campaignWebsiteUrl": "https://constructionproductscampaign.com",
      "campaignWebsiteText": "Learn More",
      "appTitle": "Construction Products App",
      "appImageUrl": "app_image.jpg",
      "appSummary": "Explore and purchase construction products on the go. Get exclusive discounts and offers!",
      "relativeUrl": null,
      "campaignItems": [
        {
          "campaignItemId": "000003000001",
          "promoTitle": "Product 000003000001",
          "promoText": "Promo text for Product 000003000001",
          "promoImgUrl": "product_image1.jpg",
          "promoImgAltText": null,
          "weight": "1",
          "teaser": "Teaser 1",
          "extraText": "Extra Text 1",
          "campaignItemDiscounts": [
            {
              "discountId": "000003000001_D",
              "tuPoints": 5,
              "altSkuImgUrl": null,
              "skuId": [],
              "discountPrice": {
                "discountId": "000003000001_D",
                "price": 20.0
              },
              "discountPercentage": null
            }
          ]
        },
        {
          "campaignItemId": "000003000002",
          "promoTitle": "Product 000003000002",
          "promoText": "Promo text for Product 000003000002",
          "promoImgUrl": "product_image2.jpg",
          "promoImgAltText": null,
          "weight": "2",
          "teaser": "Teaser 2",
          "extraText": "Extra Text 2",
          "campaignItemDiscounts": [
            {
              "discountId": "000003000002_D",
              "tuPoints": 5,
              "altSkuImgUrl": null,
              "skuId": [],
              "discountPrice": {
                "discountId": "000003000002_D",
                "price": 20.0
              },
              "discountPercentage": null
            }
          ]
        },
        {
          "campaignItemId": "000003000003",
          "promoTitle": "Product 000003000003",
          "promoText": "Promo text for Product 000003000003",
          "promoImgUrl": "product_image3.jpg",
          "promoImgAltText": null,
          "weight": "3",
          "teaser": "Teaser 3",
          "extraText": "Extra Text 3",
          "campaignItemDiscounts": [
            {
              "discountId": "000003000003_D",
              "tuPoints": 5,
              "altSkuImgUrl": null,
              "skuId": [],
              "discountPrice": {
                "discountId": "000003000003_D",
                "price": 20.0
              },
              "discountPercentage": null
            }
          ]
        }
      ]
    }
  ]
}


###
# Adding campaign.
POST /api/campaign HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJUMTQ4MzIiLCJpYXQiOjE2ODk5MzY1NDMsImV4cCI6MTY5MDA2MDAwMH0.OWGkOP9GV7RQAa_pdPJ2xQXmHqrNQz5TO5R4jVhgNuM

{
  "campaignId": null,
  "campaignFolderId": null,
  "title": "Construction Product Campaign 000001",
  "startDate": "2023-07-13T15:28:36.000+00:00",
  "endDate": "2023-08-04T18:11:16.000+00:00",
  "type": 9001,
  "promoDescriptionText": "Shop now for a wide range of construction products at discounted prices. Limited stock available!",
  "promoSummaryText": "Save Big on Construction Products",
  "ribbonType": "Special Offer",
  "termsUrl": "abc",
  "campaignClientGroups": [
    "Industrie"
  ],
  "campaignTags": [],
  "rootIndicator": true,
  "filterImgUrl": "filter_image.jpg",
  "filterOverlayText": "Limited Time Offer!",
  "promoImgUrl": "promo_image.jpg",
  "promoImgAltText": "abc",
  "campaignWebsiteUrl": "https://constructionproductscampaign.com",
  "campaignWebsiteText": "Learn More",
  "appTitle": "Construction Products App",
  "appImageUrl": "app_image.jpg",
  "appSummary": "Explore and purchase construction products on the go. Get exclusive discounts and offers!",
  "relativeUrl": null,
  "campaignItems": [
  ]
}